### ISSUE TITLE
iOS toast style not applied

### ISSUE THREAD

**Issue by rchovan** [EddyVerbruggen/Toast-PhoneGap-Plugin#102]
### Expected behaviour
toast style should be applied

### Actual behaviour
toast is visible without style

### I'm seeing this behaviour on

- [ ] iOS device
- [x] iOS sim
- [ ] Android device
- [ ] Android sim

#### OS versions
Example: iOS 10.2

### I'm not a dummy, so I've checked these
- [x] It happens on a fresh Cordova CLI project as well.
- [x] I'm waiting for `deviceready` to fire.
- [x] My JavaScript has no errors (`window.onerror` catches nothing).

### So how can we reproduce this?
```
window.plugins.toast.showWithOptions(
                {
                    message: "hey there\ncustom toast message",
                    duration: "10000", // which is 2000 ms. "long" is 4000. Or specify the nr of ms yourself.
                    position: "top",
                    addPixelsY: -40, // added a negative value to move it up a bit (default 0)
                    style: {
                        opacity: 1.0, // 0.0 (transparent) to 1.0 (opaque). Default 0.8
                        backgroundColor: '#F33334', // make sure you use #RRGGBB. Default #333333  #FFB3B3
                        textColor: '#00FF00', // Ditto. Default #FFFFFF
                        textSize: 'large', // Default is approx. 13.
                        cornerRadius: 10, // minimum is 0 (square). iOS default 20, Android default 100
                        boxShadow: '#FFB3B3',
                        horizontalPadding: 33, // iOS default 16, Android default 50
                        verticalPadding: 21 // iOS default 12, Android default 30
                    }
                }
        );
```
and here is screenshot:
![snimka obrazovky 2017-02-14 o 20 17 06](https://cloud.githubusercontent.com/assets/6713920/22945079/365e2568-f2f3-11e6-90b6-e5188768cbaf.png)

**Comment by EddyVerbruggen** [comment]
it's `styling`, not `styling`.

**Comment by rchovan** [comment]
sorry, my bad, .. but when I changed it, I can see style, but not message

![snimka obrazovky 2017-02-14 o 20 58 05](https://cloud.githubusercontent.com/assets/6713920/22946718/7f135e72-f2f8-11e6-9e20-a3e927ec019b.png)

**Comment by EddyVerbruggen** [comment]
Perhaps it's the padding (too much). Plz remove the styling and build it up again property by property.
