### ISSUE TITLE
How to detect android toast permission

### ISSUE THREAD

**Issue by qq379673328** [EddyVerbruggen/Toast-PhoneGap-Plugin#105]
When android user close app notice permission, toast can not display.
Is there anyway to detect toast permission?

**Comment by gjoris** [comment]
I haven't tried this plugin, but maybe this'll work for you?

https://www.npmjs.com/package/cordova-plugin-android-permissions

**Comment by EddyVerbruggen** [comment]
What is a Toast permission exactly?
