### ISSUE TITLE
Plugin add cordova-plugin-x-toast Error

### ISSUE THREAD

**Issue by mariahw** [EddyVerbruggen/Toast-PhoneGap-Plugin#109]
### Expected behaviour
The error started with an attempt to run:
`ionic cordova emulate ios --target='iPhone-6' -l -c -s --address localhost`

I have tried running:
`cordova plugin add cordova-plugin-x-toast`
`ionic cordova plugin add cordova-plugin-x-toast`
`phonegap local plugin add cordova-plugin-x-toast`
`cordova plugin add git+https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git`

All have returned the same error.

### Actual behaviour
(node:10489) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Failed to fetch plugin git+https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
(node:10489) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

#### Hardware models
All iPhone options

#### OS versions
I'm on macOS High Sierra 10.13.2

**Comment by shahid-ccs** [comment]
facing same issue my system os is windwos 10 and building app for android

**Comment by adeelturk** [comment]
Facing this same issue 
My system OS is Windows 10 
Building android app

**Comment by adeelturk** [comment]
Facing the same issue on windows 10 

(node:14780) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Failed to fetch plugin https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git#2.1.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.

developing app fro android

**Comment by gabn88** [comment]
Same here... weird

**Comment by trentbullard** [comment]
worked for me with just `cordova plugin add https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git`

**Comment by DOMAFirstPower** [comment]
Hi.

This solution no work for me. But same error.

Do you have other solution?

**Comment by lccmanuel** [comment]
this solution not work:
cordova plugin add https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git
![Captura de Pantalla 2019-08-22 a la(s) 12 31 30](https://user-images.githubusercontent.com/4195573/63543972-cfcfe880-c4d8-11e9-8100-2817d3a870dc.png)

Please some have the solution!
