### ISSUE TITLE
app Into the background Toast not work

### ISSUE THREAD

**Issue by OooOooosss** [EddyVerbruggen/Toast-PhoneGap-Plugin#110]
document.addEventListener("pause",this.showToast.bind(this),false)

showToast(){
    this.toast.showWithOptions({
      message: 'i am toast',
      duration: 2500,
      position: 'bottom'
    }).subscribe(result => console.log(result));
}

problem: first hide app , plugin is work . next Do the same thing , the plugin is not work . but i am click buttons to show Toast , plugin is normal work. only, app into the background not work 。sorry, my English is bad  。

**Comment by OooOooosss** [comment]
I need to app into the background to show toast . but plugin is not normal work .

**Comment by emrevural20** [comment]
Yes same problem. Any solution or comment ?

**Comment by EddyVerbruggen** [comment]
AFAIK your app can't show Toast messages when in the background. That would be kind of a hell for users if all apps did this, no?

**Comment by Jeijie** [comment]
@OooOooosss 在Android 8.1.0版本的华为Honor 8X上测试，Toast不显示，回调方法是执行成功了
