### ISSUE TITLE
How to remove the Android shadow?

### ISSUE THREAD

**Issue by spinninghamster** [EddyVerbruggen/Toast-PhoneGap-Plugin#111]
I can't figure out how to remove the Android blackish drop shadow ...anyone know?

**Comment by timbru31** [comment]
It's hardcoded and currently can't be changed: https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin/blob/master/src/android/nl/xservices/plugins/Toast.java#L134-L136

**Comment by EddyVerbruggen** [comment]
Yep. Feel free to send a PR to make it configurable. Much like this property: https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin/blob/4324168d2a5848028881ec075b5a741221286350/src/android/nl/xservices/plugins/Toast.java#L69 (make sure the default stays as-is).
