### ISSUE TITLE
How to change the logo on the toast

### ISSUE THREAD

**Issue by barrypearseburke** [EddyVerbruggen/Toast-PhoneGap-Plugin#115]
On android, When i make a toast, everything works however the icon has the cordova logo on the side of the toast. It looks well, But this logo doesn't appear in the doc screen shots and im wondering is it just me. And if so, how can i change it or remove it 

![logooftoast](https://user-images.githubusercontent.com/6729768/37616377-9ef17c4a-2ba7-11e8-877a-ad9788130a74.png)

**Comment by EddyVerbruggen** [comment]
Which plugin are you using exactly, according to package.json/config.xml? This one doesn't support icons..

**Comment by barrypearseburke** [comment]
"cordova-plugin-x-toast": "^2.6.2",

Followed instructions on downloading form 
https://www.npmjs.com/package/cordova-plugin-x-toast

**Comment by EddyVerbruggen** [comment]
I have no idea where that logo comes from.

**Comment by barrypearseburke** [comment]
Glad i could add a new feature :)
