### ISSUE TITLE
Toast not shown in Android P

### ISSUE THREAD

**Issue by spragadheeshraj** [EddyVerbruggen/Toast-PhoneGap-Plugin#116]
The toast is not shown on Pixel 2 running Android P. It does not provide any error message
- [x] Android device not sure on other devices (Tested with Pixel 2)
- [x] My JavaScript has no errors (`window.onerror` catches nothing).

**Comment by danfleck** [comment]
Just confirming I have a similar problem. On Pixel 2 if I press a button that should show the toast, it shows if I press the button a few times, but never on the first time. Possibly a timing issue of some type.

**Comment by greenlightsaber** [comment]
I have the same issue with the recent Android P update on Pixel.

**Comment by patrickfrisch** [comment]
This pull request will fix it in my case: https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin/pull/118

Hope it could help you.

**Comment by spragadheeshraj** [comment]
@patrickfrisch Thank you! I just tried it and it works fine now!

**Comment by snipking** [comment]
This bug also exist on MIUI V10 based on Android Oreo. Pull request #121
