### ISSUE TITLE
Toast not shown in Honor 8XS

### ISSUE THREAD

**Issue by Jeijie** [EddyVerbruggen/Toast-PhoneGap-Plugin#120]
### Expected behaviour
show Toast

### Actual behaviour
Toast not shown in Honor 8X

### I'm seeing this behaviour on

- [ ] iOS device
- [ ] iOS sim
- [x] Android device
- [ ] Android sim

#### Hardware models
Honor 8X
Android 8.1.0

#### OS versions
ExCordova CLI: 6.5.0
Ionic Framework Version: 1.2.4
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
OS: Windows 7 SP1
Node Version: v10.8.0

### I'm not a dummy, so I've checked these
- [ ] It happens on a fresh Cordova CLI project as well.
- [x] I'm waiting for `deviceready` to fire.
- [x] My JavaScript has no errors (`window.onerror` catches nothing).

**Comment by DGGohil** [comment]
Remove this line from your index.html file <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">  and add below one.. 

...
 <meta http-equiv="Content-Security-Policy" content="default-src * gap: ws: https://ssl.gstatic.com;style-src * 'unsafe-inline' 'self' data: blob:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;img-src * data: 'unsafe-inline' 'self' content:;media-src mediastream;">

**Comment by zhzhch335** [comment]
Try subscribe it with empty even:
this.toast.showShortCenter("再次点击返回键退出").subscribe();
In my project it works.
BTW my device is Honor V10.
I don't know its reason....

**Comment by DGGohil** [comment]
I do have Honor V10 and i didn/t tried with .subscribe() , mine worked by doing above method.

**Comment by NorthFred** [comment]
It seems that the toast notifications do not show on Android 8+ when using the latest versions of the plugin.

I removed the latest plugin from my project and went back to 2.5.2, and the toasts are working on at least Android 8.0 (e.g. Huawei P Smart) and Android 8.1 (Honor 7S).

`ionic cordova plugin rm cordova-plugin-x-toast
ionic cordova plugin add cordova-plugin-x-toast@2.5.2`

**Comment by Jeijie** [comment]
@NorthFred  It no works in Honor 8X，Android 8.1.0

**Comment by Jeijie** [comment]
@DGGohil I had tried with  .subscribe() , but it no worked by doing above method.

**Comment by DGGohil** [comment]
> @DGGohil I had tried with .subscribe() , but it no worked by doing above method.

PM me your index.html.

**Comment by Jeijie** [comment]
@DGGohil  Whether or not there is a sentence above. It doesn't work.

  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width, viewport-fit=cover">
  <meta http-equiv="Content-Security-Policy" content="default-src * gap: ws: https://ssl.gstatic.com;style-src * 'unsafe-inline' 'self' data: blob:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;img-src * data: 'unsafe-inline' 'self' content:;media-src mediastream;">
  <title></title>

**Comment by Jeijie** [comment]
@DGGohil 

Whether or not there is a sentence above. It doesn't work.



 meta charset="utf-8"
 meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width, viewport-fit=cover"

 meta http-equiv="Content-Security-Policy" content="default-src * gap: ws: https://ssl.gstatic.com;style-src * 'unsafe-inline' 'self' data: blob:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;img-src * data: 'unsafe-inline' 'self' content:;media-src mediastream;"

**Comment by Zhang1051127659** [comment]
I also encountered this problem, and my device is Xiaomi 8, Android 8.1

**Comment by Jeijie** [comment]
### I also integrated cordova-plugin-toastyplugin to my project, it works for me.


 if (window.cordova&&window.plugins.toastyPlugin) {
        window.plugins.toastyPlugin.show(message, 1000, function () {
          console.log('totoastyPluginast success');
        }, function () {
        });
      }else if (window.cordova&&window.plugins.toast) {
        window.plugins.toast.showShortCenter(message, function (res) {
          console.log('toast success');
         }, function () { });
      } else {
        alert(message);
      }

**Comment by Zhang1051127659** [comment]
> ### I also integrated cordova-plugin-toastyplugin to my project, it works for me.
> if (window.cordova&&window.plugins.toastyPlugin) {
> window.plugins.toastyPlugin.show(message, 1000, function () {
> console.log('totoastyPluginast success');
> }, function () {
> });
> }else if (window.cordova&&window.plugins.toast) {
> window.plugins.toast.showShortCenter(message, function (res) {
> console.log('toast success');
> }, function () { });
> } else {
> alert(message);
> }

Are you talking about [ToastyPlugin](https://github.com/iamarzuza/ToastyPlugin)? I installed it, but I saw that the source code inside it is not very reliable, actually there is alert
![image](https://user-images.githubusercontent.com/19969080/48247872-f207e680-e42f-11e8-8483-de16de5fdb90.png)

**Comment by Jeijie** [comment]
Year!, it seems that debug info , you can removew it  manually.

**Comment by Jeijie** [comment]
@Zhang1051127659 

Yeah!, same issue I  encountered , you need remove it manually and install again.
![image](https://user-images.githubusercontent.com/9338052/48250639-f0dbb700-e439-11e8-802d-52d436a890cd.png)

**Comment by 442623641** [comment]
it work for me:
Toast.java, find
`private static final boolean IS_AT_LEAST_PIE = Build.VERSION.SDK_INT >= 28;`
replace with
`private static final boolean IS_AT_LEAST_PIE = Build.VERSION.SDK_INT >= 26;`

**Comment by EddyVerbruggen** [comment]
Published 2.7.1 which removes the problematic code entirely.
