### ISSUE TITLE
Crash from API 30

### ISSUE THREAD

**Issue by merbin2012** [EddyVerbruggen/Toast-PhoneGap-Plugin#141]
I think this is very old and unmaintained.  I had to get more crashes related to this toast plugin. But while testing on API 30 device it worked, but with some error on the android studio console, and if we call many times apps crashed while testing. So I strongly recommended you do not use this plugin until release a new update.
Currently, I am replacing it with the following plugin, **cordova-plugin-simple-toast** and it works for now, but don't know about full feature.

**Comment by bftcntyapps** [comment]
Any chance this plugin will get updated? Crashing on Android 30 and app closes after the user touches the screen after a toast.

**Comment by laurentperez** [comment]
Same question. Is there an alternative ? cordova-plugin-simple-toast looks old too

**Comment by merbin2012** [comment]
@laurentperez yeah, right. But no crash rate compare to this plugin

**Comment by tomburger** [comment]
Hi all, I have created pull request #142, which solved the issue for me.

**Comment by zommerfelds** [comment]
@merbin2012 I think we can close this, given that the main issue was fixed in #142?
That solved my problem at least.

**Comment by merbin2012** [comment]
@zommerfelds Sure. Not yet been checked and I hope this issue was fixed.

**Comment by GuganRajs** [comment]
PLEASE FOLLOW THIS LINK 100% WORKING https://github.com/ns0m/cordova-plugin-ns0m-x-toast/pull/2/files.
