### ISSUE TITLE
option for a shorter duration

### ISSUE THREAD

**Issue by louisdoe** [EddyVerbruggen/Toast-PhoneGap-Plugin#15]
Hi Eddy

thanks for this plugin !

Is it possible to make the toast last shorter than with the "short" option ?

thanks

**Comment by dorian-marchal** [comment]
Same here, I'd need a longer duration :+1:

**Comment by EddyVerbruggen** [comment]
This landed a while ago, forgot to close it.

**Comment by ravi-pandit14** [comment]
is this possible to set toast duration time infinite????
