### ISSUE TITLE
Request: Add left right center options

### ISSUE THREAD

**Issue by epelc** [EddyVerbruggen/Toast-PhoneGap-Plugin#16]
I think it would be nice if we specify the position of toast messages not only vertically but also horizontally. This is not only visually more appealing for some but it's also used by material design which for the bottom right corner toast elements, and I think a lot of apps would like to switch to that when it is more stable.

**Comment by udeeps** [comment]
Any update on this enhancement? Also, is it possible to to add option to left, right and center align text INSIDE the toast? Right now, my text are only left alligned in the toast and doesn't look good when there are multiple lines.

**Comment by peepsilog** [comment]
You have to edit the plugin, based on your liking.

**Comment by udeeps** [comment]
thanks @peepsilog , I will try that.
