### ISSUE TITLE
Can we test this plugins in browser?

### ISSUE THREAD

**Issue by vipulsodha-zz** [EddyVerbruggen/Toast-PhoneGap-Plugin#19]
Can we test this plugins in browser? Mine throws error when tested in browser?

**Comment by shprink** [comment]
Is it possible to re-open that and actually create the browser platform version? http://www.raymondcamden.com/2014/09/24/Browser-as-a-platform-for-your-PhoneGapCordova-apps

**Comment by shprink** [comment]
```cordova platform add browser```

**Comment by timbru31** [comment]
It's been two years, but it seems https://github.com/apache/cordova-browser is picking up speed - it would be awesome if this issue can be re-opened!

**Comment by EddyVerbruggen** [comment]
I love the idea of having a browser implementation, but that has to go the PR route..
