### ISSUE TITLE
Click event

### ISSUE THREAD

**Issue by Hirbod** [EddyVerbruggen/Toast-PhoneGap-Plugin#20]
Hi Eddy,

very nice plugin! Thank you. Is it possible to add some arguments and a click event on this toast notification? I like to display chat messages (received trough sockets) and when the user clicks on the bubble, redirect to the specific 1on1 chat view. Something like WhatsApp.

**Comment by MikeBazhenov** [comment]
+1

**Comment by leandro-shifteight** [comment]
Could be awesome to have a click handler for the Toast!

**Comment by jkuri** [comment]
+1

**Comment by Hirbod** [comment]
Any chance to get this someday? One year passed...

**Comment by EddyVerbruggen** [comment]
2.3.0 published, with this new feature: https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin#receiving-a-callback-when-a-toast-is-tapped, let me know what you think :+1:

**Comment by Hirbod** [comment]
Well suddenly it was done :D. Thanks. There is really one thing left from being perfect. The ability to store data (json object) on that toast. Now I have a click event, but I guess it is useless when you don't know what to do with it. I want to show a toast on a socket message, on click, navigate my app somewhere. But to make a appropiate click (eg redirecting to a specific chat room), there has to be some functionality. Of course I could store something in local storage or rootscope before, but it would be nice if there could be something inside of the callback, even when it's just the same passed data

**Comment by EddyVerbruggen** [comment]
In 2.3.1 you can pass in a `data` JSON object which you'll get back in the success callback. Let me know if that works for you.

**Comment by Hirbod** [comment]
Looked over the code, seems promising. I will test it later that day or tomorrow. Thank you so much Eddy. Do you have PayPal? Would like to spend you a beer.

**Comment by EddyVerbruggen** [comment]
That's awesome! My paypal is my gmail: eddyverbruggen@..
Thx!

**Comment by Hirbod** [comment]
- gmail.com or googlemail.com ?

**Comment by EddyVerbruggen** [comment]
gmail.com, sorry

**Comment by Hirbod** [comment]
Beer is on it's way.

**Comment by EddyVerbruggen** [comment]
Much appreciated

**Comment by Hirbod** [comment]
:beer:
