### ISSUE TITLE
Notifications while app is suspended

### ISSUE THREAD

**Issue by danda1man** [EddyVerbruggen/Toast-PhoneGap-Plugin#23]
I noticed that the Notifications will show (for sure on android, haven't tried to replicate on iOS yet) even if my app is not the currently active app.  It would be nice if the Notifications wouldn't popup when my app is not the one actively being used.

**Comment by EddyVerbruggen** [comment]
Hi @danda1man does it happen while going to the background (confirmed and just fixed), or also when your app is in the background for a while and it suddenly shows a (scheduled) toast?

**Comment by danda1man** [comment]
It happens after a while as well, i was using a toast in the offline/online event callbacks and those would appear long after my app was in the background

**Comment by EddyVerbruggen** [comment]
Alright, with the new 2.0.3 release this should no longer happen on Android (didn't try others). Can you please verify and close this issue?

Thanks,
Eddy

**Comment by danda1man** [comment]
Looks good!

**Comment by BudgieInWA** [comment]
Why is this not configurable?! The unique feature of toasts on Android is that they stick around no matter what. It's my only criteria for choosing a Toast over existing UI.
