### ISSUE TITLE
Icon/Image/Url into notification. How?

### ISSUE THREAD

**Issue by biapar** [EddyVerbruggen/Toast-PhoneGap-Plugin#24]
It's possible to pass an icon ( or url to an image ) to display into notification message? How pass an URL and click on it into the message?

**Comment by EddyVerbruggen** [comment]
Nope, it's a read-only beast.

I'm considering extending it with images, but not a URL.

**Comment by biapar** [comment]
Is there some Cordova plugin for this?

**Comment by EddyVerbruggen** [comment]
For the image or a tappable link?

**Comment by biapar** [comment]
For a tappable link with an image icon...

**Comment by EddyVerbruggen** [comment]
Don't think so, I'm afraid you'll have to resort to HTML for that.

**Comment by zapnap** [comment]
Just to clarify, there's no way to insert a clickable link into a native toast, correct? The use case I'm looking for is a simple "undo" button. I'd need to resort to some sort of html flash message instead?

**Comment by EddyVerbruggen** [comment]
@zapnap That's not possible, at least it's not on Android afaik. You could try using an [ActionSheet](https://github.com/EddyVerbruggen/cordova-plugin-actionsheet) instead.

**Comment by zapnap** [comment]
Thanks for clarifying. I guess I was looking for something like this https://github.com/soarcn/UndoBar

**Comment by Ahiaz** [comment]
if you need image with toast you can use my modified library: https://github.com/Ahiaz/toast_with_image
