### ISSUE TITLE
Windows phone 8.1

### ISSUE THREAD

**Issue by andreapozzetti** [EddyVerbruggen/Toast-PhoneGap-Plugin#25]
When Windows phone 8.1 version?

Thanks

**Comment by EddyVerbruggen** [comment]
Doesn't it work?

**Comment by andreapozzetti** [comment]
no

**Comment by EddyVerbruggen** [comment]
That's unexpected as I have a WP 8.1 device with the plugin working.

Can you show me your project? Not just a sample, all of it please.
