### ISSUE TITLE
Support Crosswalk backend

### ISSUE THREAD

**Issue by eborned** [EddyVerbruggen/Toast-PhoneGap-Plugin#26]
When using the 'new' Crosswalk backend, the webView variable is not (directly?) available. So, the call to webView.isPaused() returns an error. For now, I've disabled this block of code in my build.

**Comment by MyBoon** [comment]
Yes same issue for me.
cannot find symbol  : method isPaused()

**Comment by EddyVerbruggen** [comment]
Hey guys, thanks for reporting and confirming this issue.

Please test the new 2.0.4 version of the Toast plugin.
