### ISSUE TITLE
Toast runs in background and eats up a lot of battery on android only

### ISSUE THREAD

**Issue by shfaizanali** [EddyVerbruggen/Toast-PhoneGap-Plugin#31]
I recently integrated Cordova plugin with Toast and while the app is in background the toasts keep coming up (I display a toast on network going online/offline). Is anyone else facing the problem ? This is producible on android only, iOS is running dine

**Comment by EddyVerbruggen** [comment]
Hi, which version of the plugin are you on? In more recent versions the Toasts should not show up when the app is paused ([because of this](https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin/blob/master/src/android/nl/xservices/plugins/Toast.java#L32-L34)).

**Comment by shfaizanali** [comment]
Its reproducible for me in version 2.0.2 which is the latest one

**Comment by EddyVerbruggen** [comment]
Hi @shfaizanali I found the person why uploaded this plugin to the [cordova plugin registry](http://plugins.cordova.io/#/package/nl.x-services.plugins.toast) and kindly asked him to update to the latest version which he did, so please update your app.
