### ISSUE TITLE
Customization for toasts?

### ISSUE THREAD

**Issue by inexion** [EddyVerbruggen/Toast-PhoneGap-Plugin#32]
More of a feature request, but would it be possible to offer some customization for how these look on a given phone?

**Comment by EddyVerbruggen** [comment]
Any specific wishes? It depends largely on the platform what is possible by the way.

**Comment by inexion** [comment]
I'd like to be able to style:

- border radius
- background color
- font color, and other css properties (size, face, weight)
- width

Platform-wise, I guess iOS and Android, maybe just iOS to start.

**Comment by EddyVerbruggen** [comment]
Are you building your app locally? Then you could consider doing it right away by playing with these properties: https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin/blob/master/src/ios/Toast%2BUIView.m#L11-L40

**Comment by inexion** [comment]
I am not - I'm using the ionic framework. I guess it'd be more of a feature request for ngCordova, or at least opening up those properties so ngCordova could access them. Although I could just edit the plugin code as well :]

**Comment by EddyVerbruggen** [comment]
Yeah, that last bit is what I meant. If you're building locally (not PhoneGap Build) then editing that file should be pretty easy, even without any experience in native code.

**Comment by inexion** [comment]
Cool, will do - thanks!
