### ISSUE TITLE
Close toast when app is suspended or closed.

### ISSUE THREAD

**Issue by napcat** [EddyVerbruggen/Toast-PhoneGap-Plugin#35]
If a toast is called and I minimize the app the toast continues active.

I was hopping for a closeAll method to call on app pause, or an automatic way to close/hide the toast if the app is minimized.

**Comment by EddyVerbruggen** [comment]
That should actually work. Which OS and which plugin version is this?

**Comment by napcat** [comment]
I'm on android version 4.4.4, but his also happens on Android 5 (CM12).

The plugin version is "nl.x-services.plugins.toast 2.0.4 'Toast'"and the project is using the latest Cordova 5.0.

At this moment I didn't test on WP8 and iOS but I could make some tests later.

The toast appears, a hit home button, the app minimizes and the toast is still visible...

**Comment by EddyVerbruggen** [comment]
Cordova-Android 4+ is probably the culprit, I will check it. I know for sure iOS doens't have this issue btw.

**Comment by EddyVerbruggen** [comment]
Hmm, tried Cordova-Android 4 (Cordova CLI 5) with Android 4.3 and 5.0 and it's fine: show a toast, press home, the Toast immediately fades out (this takes half a second). I hoped to reproduce this..

Can you post a little video of what you're seeing perhaps? Maybe it can put me on the right track.

**Comment by EddyVerbruggen** [comment]
Hi, I've added a new `hide()` function for all platforms, just in case if you still have the problem, you can try to use it onPause.
