### ISSUE TITLE
Is it possible to add a position?

### ISSUE THREAD

**Issue by ctl1690** [EddyVerbruggen/Toast-PhoneGap-Plugin#36]
In here.
![screenshot-ios-toast](https://cloud.githubusercontent.com/assets/2221790/7718308/fb54e180-fee0-11e4-853b-52fb8af8fc38.png)

Because the bottom position always show the tool bar or AD.
Is it possible to avoid covering display it？

**Comment by EddyVerbruggen** [comment]
Hi, do you build locally (have control over iOS sourcecode)?

**Comment by ctl1690** [comment]
Yes, same problem.

If the toast showed a little higher position, I think user experience will be better.

**Comment by EddyVerbruggen** [comment]
Hi guys, while waiting for me to finally make the positions fully configurable I've lowered the top one a bit and moved the bottom one a bit up (iOS only).

**Comment by ctl1690** [comment]
Thanks a lot.
Does Andriod can not configurable ?

**Comment by EddyVerbruggen** [comment]
Yes you can tweak the notification height for Android as well, see [this line](https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin/blob/master/src/android/nl/xservices/plugins/Toast.java#L61)

**Comment by ctl1690** [comment]
Thanks.
Is possible to provide api to configure position by javascript?

**Comment by EddyVerbruggen** [comment]
Ghehe, absolutely, I should make some time for that..

**Comment by ctl1690** [comment]
Thanks a lot.
Alothough I changed the java code.
But I think this not good idea to change native code of plugin,that inconvenient to update.

Thank your plugin, this very useful.

**Comment by rodrigograca31** [comment]
Hi @EddyVerbruggen!
First, thanks for the plugin!

The plugin shows up over the ads when using admob....
When using admob everything goes up... but not this plugin...
I'm using this plugin: https://github.com/floatinghotpot/cordova-admob-pro

Here is a screenshot of how it looks:
![screenshot_2015-06-11-16-25-28](https://cloud.githubusercontent.com/assets/1134310/8111022/387f3f42-1057-11e5-8be2-b43e1cfb73a2.png)

**Comment by EddyVerbruggen** [comment]
Working on this feature right now!

**Comment by EddyVerbruggen** [comment]
@ctl1690 @rodrigograca31 By popular demand (thanks for asking!) you can now control the vertical position on iOS, Android and WP!

Look for `showWithOptions` in the updated README and make sure to add `addPixelsY`. Any number (positive or negative) will be added to the position you pass in. So for example this will show a short toast near the bottom, but a bit more upwards than you were used to:

```js
            window.plugins.toast.showWithOptions(
                  {
                    message: "hey there",
                    duration: "short",
                    position: "bottom",
                    addPixelsY: -60  // default 0
                  }
            );
```

:beers:

**Comment by rodrigograca31** [comment]
@EddyVerbruggen Thanks! You are the best :smile: 
This is why I love open source! ;)

In my case I had to add -150 pixels (ad size)

![screenshot_2015-06-12-02-51-17](https://cloud.githubusercontent.com/assets/1134310/8122186/3c169662-10ae-11e5-91da-b7b468486ffb.png)

**Comment by ctl1690** [comment]
@EddyVerbruggen Thanks a lot. This plugin is very very useful.
