### ISSUE TITLE
Toast-PhoneGap-Plugin message not orientated properly on iOS devices

### ISSUE THREAD

**Issue by rahulsalvikar777** [EddyVerbruggen/Toast-PhoneGap-Plugin#37]
Please refer this link for issue 
http://stackoverflow.com/questions/30865374/phonegap-toast-plugin-not-working-on-ios

**Comment by rynangeles** [comment]
for me, i was not able to display and toast in my app

**Comment by EddyVerbruggen** [comment]
@rynangeles How are you using the plugin?

**Comment by rahulsalvikar777** [comment]
Hi all, I push the demo code on git hub please refer the below link. https://github.com/rahulsalvikar777/toastPluginDemo.git

Steps for creating the application.
1) I create my project in ionicframework
2) I add ngcordova lib and follow the below tutorials 
    a) http://ngcordova.com/docs/plugins/toast/
    b) https://blog.nraboy.com/2014/09/show-native-toast-notifications-using-ionic-framework/
3) In iOS platform, I check all the rotations and build/ run the code. 

When you run the project on iOS device you can see the menu, please select the browse menu and rotate the ios device and press any key. then you can see the issue

**Comment by EddyVerbruggen** [comment]
Can't reproduce on my iPhone 6, perhaps I'm doing something wrong - see the vid.

![landscape-toast](https://cloud.githubusercontent.com/assets/1426370/8250145/638964b8-1671-11e5-9d89-3c2a2d352bcd.gif)

**Comment by rahulsalvikar777** [comment]
May be....
I got same  issue  message not rotating :( .
 
Below steps which I use for reproduce that problem
1) Select all Device orientation in XCode and then run code on device.

I am using 1) iPhone 4s and iOS 7.1.2 , 2)  iPad ios 7.1.2

![photo](https://cloud.githubusercontent.com/assets/928034/8250476/e71d431a-1691-11e5-9e21-92006d89d139.PNG)

**Comment by EddyVerbruggen** [comment]
Hmm, smells like an iOS7 issue.. do you have any iOS8 device you can test on?

**Comment by rahulsalvikar777** [comment]
Woooo, It OS issue I test on simulator now. Its working properly. But still its not working on iOS 7. Thanks for help may be in next update this issue will be resolved. :)

**Comment by EddyVerbruggen** [comment]
Just reproduced this in the iOS 7 simulator as well, let me try to fix it..

**Comment by EddyVerbruggen** [comment]
Hi, please try the master branch, it should now be compatible with landscape on iOS 7.

**Comment by jcesarmobile** [comment]
changing 
 [self.superview.superview addSubview:toast];
to
 [self.superview addSubview:toast];

seems to fix the issue, but might cause others

**Comment by EddyVerbruggen** [comment]
Lol
