### ISSUE TITLE
Enhancement: Possibility to style the toast

### ISSUE THREAD

**Issue by zarko-tg** [EddyVerbruggen/Toast-PhoneGap-Plugin#4]
Would be neat to be able to configure at least a background color for the toasts.
Is it technically possible on both supported platforms?

**Comment by OlivierCo** [comment]
It's quite easy to do it for both platform...

**Comment by unr** [comment]
@OlivierCo Your comment isn't helpful.

How is it easy to do for both platforms? Do you have an example?

**Comment by danielgolub** [comment]
Are there any updates over this?

**Comment by fattalgazi** [comment]
I want to show a red background colored toast message, how can I do that? any update ?

**Comment by EddyVerbruggen** [comment]
Let me give this a try now..

**Comment by EddyVerbruggen** [comment]
Got this working on Android (not released yet, so just FYI).
Not passing in the `styling` object will fall back to what you're used to:

```js
      window.plugins.toast.showWithOptions({
        message: 'Toooooast',
        duration: 'long',
        position: 'bottom',
        styling: {
          backgroundColor: '#FF0000', // red
          borderRadius: 30, // a bit less than default, 0 means a square Toast
          alpha: 180, // 0-255, 0 being fully transparent
          padding: {
            top: 20,
            right: 30,
            bottom: 20,
            left: 30
          }
        }
```

I will need to look at iOS to make sure these property names make sense.

**Comment by fattalgazi** [comment]
You are just awesome, I'm waiting iOS version too, now. Thank you for fast response.

**Comment by EddyVerbruggen** [comment]
iOS implementation is ready to go locally but I need to do a little rework to update the Android API as this is what I've now settled for:

```js
  styling: {
    backgroundColor: '#FF0000',
    cornerRadius: 16,
    opacity: 0.75, // 0.0 to 1.0 just like CSS
    horizontalPadding: 16, // iOS uses the same values for left and right and it makes sense to keep it simple like this
    verticalPadding: 12 // ditto
  }
```

Of course you can pass in the same values for styling on iOS and Android, but if you want to use different values you can easily do:

```js
  styling: {
    cornerRadius: iOS ? 16 : 20,
  }
```

Where `iOS` is a variable you can f.i. get from the device plugin.

i hope this makes sense and I'll try to wrap this up tomorrow.

**Comment by fattalgazi** [comment]
Thank you so much for your effort beforehand. Waiting your commit impatiently.

**Comment by zarko-tg** [comment]
To whom it may concern :)
For more advanced needs (on an Angular project) one can use https://github.com/Foxandxss/angular-toastr instead of this plugin.

**Comment by Hirbod** [comment]
The big difference between a native and an angular solution is, that this plugin is always on the highest view - even above inappbrowser. If most-top isn't important for you, grab angular, if not, this plugin is the best shot (less Dom nodes, smoother animation, background threads / non blocking.

**Comment by EddyVerbruggen** [comment]
Hey guys, thanks for the assistance and discussions in this issue.

I've now released 2.4.0 to npm which allows styles like these (iOS screenshots):

<img width="254" alt="styling-green" src="https://cloud.githubusercontent.com/assets/1426370/12626214/d4df96da-c537-11e5-9350-41c02aefaf80.png">
<img width="330" alt="styling-red" src="https://cloud.githubusercontent.com/assets/1426370/12626215/d4e0a282-c537-11e5-8659-57fcb392e56a.png">

Check out the readme for details!

:beers: 
Eddy

**Comment by unr** [comment]
Fantastic, Thanks @EddyVerbruggen :)

**Comment by fattalgazi** [comment]
You are just God damn perfect ! Thank you @EddyVerbruggen
