### ISSUE TITLE
show the pop up on the front of call screen

### ISSUE THREAD

**Issue by 7aduta** [EddyVerbruggen/Toast-PhoneGap-Plugin#40]
can i show the pop up on the front of call screen ?

**Comment by EddyVerbruggen** [comment]
Nope, you can only show it on top of your own app.

But you may be interested in Local Notifications. There's a great plugin for that.

**Comment by 7aduta** [comment]
i want to make a pop up window on the call screen ... so i could show the details of the caller 
is there a pohne gap plugin that gets the caller number and do an ajax to the site and return the details to the app th show the data on the pop up on the call screen ?

**Comment by EddyVerbruggen** [comment]
I think you will get a better response to this question when you post it on StackOverflow.

If you're targeting Android you may find [this](https://github.com/devgeeks/PhoneListener/tree/extended) useful for receiving the incoming number. [This line of code](https://github.com/devgeeks/PhoneListener/blob/extended/PhoneListener.java#L74) to be specific.

For iOS the closest API I could find was [this](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Reference/CTCallCenter/index.html#//apple_ref/occ/instp/CTCallCenter/currentCalls) but I doubt it that it will contain the actual phone number of the incoming call.

**Comment by 7aduta** [comment]
i already did but no luck
http://stackoverflow.com/questions/31257786/phonegap-get-caller-number-and-add-pop-up-on-call-window

i'm not an androoid developer so .. i couldn't make what i want !!
