### ISSUE TITLE
add plugin to npm 

### ISSUE THREAD

**Issue by aliokan** [EddyVerbruggen/Toast-PhoneGap-Plugin#41]
Could you add your plugin ton npm? 
https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

Thank you! :)

**Comment by EddyVerbruggen** [comment]
Yes I will soon :)

**Comment by aliokan** [comment]
Great!

**Comment by iosipeld** [comment]
+1 :)

**Comment by martinoss** [comment]
+1

**Comment by EddyVerbruggen** [comment]
[Enjoy](https://www.npmjs.com/search?q=cordova-plugin-x-toast)!
