### ISSUE TITLE
toast not showing on top of InAppBrowser on iOS

### ISSUE THREAD

**Issue by hasandogu** [EddyVerbruggen/Toast-PhoneGap-Plugin#42]
When InAppBrowser is shown on the screen the toast isn't visible to the user. I have tested on device and the simulator with iOS 8.

Seems like self.superview.superview is nil at 
https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin/blob/50290d83deab9db09837ff4ca2cb8dc285c0e8ab/src/ios/Toast%2BUIView.m#L118 

This happens with cordova-plugin-inappbrowser version 0.6.0 as well as the latest 1.0.2 with Toast-PhoneGap-Plugin 2.1.1.

**Comment by EddyVerbruggen** [comment]
Hi @hasandogu please use version 2.2.1 because I finally found a fix for this issue.

**Comment by hasandogu** [comment]
I've just tested this. Thanks so much!

On Tue, Sep 29, 2015 at 1:38 PM, Eddy Verbruggen <notifications@github.com>
wrote:

> Hi @hasandogu <https://github.com/hasandogu> please use version 2.2.1
> because I finally found a fix for this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin/issues/42#issuecomment-144184820>
> .
>



-- 

[image: --]
Hasan Dogu Taskiran
[image: http://]about.me/hasandogu
<http://about.me/hasandogu>
