### ISSUE TITLE
App crash, Crosswalk, Samsung Galaxy S3

### ISSUE THREAD

**Issue by SandroGrzicic** [EddyVerbruggen/Toast-PhoneGap-Plugin#43]
I have found a reproducible crash that happens when a Toast is opened on the Samsung Galaxy S3, but not on other phones like the Samsung S4 Mini (with Android 4.4.4), Sony Z3 Compact (Android 5), Nexus 5 (Android 5.1), etc. 

I'm using Cordova 5.11, platform android 4.1.0, nl.x-services.plugins.toast 2.1.1. Crosswalk version is 14.43.343.17.

Here's a pastebin of the logcat log when I want to open a toast using `window.plugins.toast.show("My Text", 'short', 'bottom'):`

https://pastebin.com/wygC7yA3

The phone is a freshly factory-reset Samsung Galaxy S3 (GT-I9300) running Android 4.3.

Any idea what the crash is about? To be honest it doesn't look like the plugin is at fault, it just seems to trigger it. Perhaps a memory issue, or a Crosswalk issue? I noticed there's a `webView.getContext()` call in your `Toast.makeText`, but I cannot see how this would be a problem.

Thanks for any help.

**Comment by SandroGrzicic** [comment]
Hi,

it's definitely not the Toast plugin as the same crash happens while using the InAppBrowser plugin:

https://pastebin.com/BJcUcp5k

Seems like a Cordova issue.

Thanks anyway.

**Comment by SandroGrzicic** [comment]
After some more investigation apparently the problem was caused by using android:Theme.Material in a pre-Lollipop device and has nothing to do with Cordova, Crosswalk or this plugin.

**Comment by EddyVerbruggen** [comment]
Thanks for all the updates, much appreciated. Hopefully in the future someone will benefit from it.
