### ISSUE TITLE
Toast looks blurry on android 5.1.1

### ISSUE THREAD

**Issue by martinoss** [EddyVerbruggen/Toast-PhoneGap-Plugin#44]
I just noticed, that the toast looks blurry on Android 5.1.1 (Samsung Galaxy S6 Edge). On Android 4.4 it looks sharp (HTC One M7).

After some research, it turned out, that if I change [this line](https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin/blob/50290d83deab9db09837ff4ca2cb8dc285c0e8ab/src/android/nl/xservices/plugins/Toast.java#L55) to `cordova.getActivity().getApplicationContext()`, it looks okay on both devices.

Screenshot from same device (s6), plugin version 2.1.1 and modified:
![toasts](https://cloud.githubusercontent.com/assets/2587942/9069520/195b11a0-3aea-11e5-8fcd-f71603b7e262.png)

**Comment by EddyVerbruggen** [comment]
Wow, nice find - would you mind making a pull request to change the line?
