### ISSUE TITLE
window.plugins.toast.showWithOptions doesn't work

### ISSUE THREAD

**Issue by artistika** [EddyVerbruggen/Toast-PhoneGap-Plugin#46]
When i install the plugin (cordova) and try to call this function it isn't recognized (window.plugins.toast.showWithOptions is not a function). Just show and those 6 other are only available. Tested on Android only.

**Comment by EddyVerbruggen** [comment]
How do you install the plugin, and which version do you get?

**Comment by artistika** [comment]
cordova plugin add...
version 2.0.4

**Comment by artistika** [comment]
I see now that the update is from 2.1.0+ so i should install specific version of the plugin. 
Like this it gets v2.0.4, don't know why.

**Comment by rajamohammed** [comment]
It throws "Class not fount" error in error call back . below is the code snippet im using. 
```
var toast = function (mes,dur,pos) {
  window.plugins.toast.showWithOptions(
    {
      message: mes,
      duration: dur,
      position: pos,
      addPixelsY: -40  // added a negative value to move it up a bit (default 0)
    },function(){
      
    },function(e){
      console.debug(e);
      console.log('error');
    }
  
  );
};
```
//Function call 
```
 toast('Toast Message','short','bottom');
```

**Comment by EddyVerbruggen** [comment]
Is there a `Toast` class in your project? Which platform is this? And which device/version.

**Comment by rajamohammed** [comment]
Added the plugin cordova cli command , Im using it in 'Ionic' project . Device - Android 4.1

**Comment by EddyVerbruggen** [comment]
Is there a `Toast.java` class in your `platforms/android/...` folder? Perhaps try `cordova prepare` as well after adding the plugin.

**Comment by rajamohammed** [comment]
Yeah its available in platforms/android/src/x-service/plugins/Toast.java  

Did cordova prepare as well still the same .

**Comment by EddyVerbruggen** [comment]
Dunno then, if you can't figure it out feel free to send me your project at eddyverbruggen at gmail.

**Comment by rajamohammed** [comment]
Ahh .. Mistake . i have been testing it on ionic --livereload mode . 

It works perfect in device :+1:  :100: 

Thank you for the wornderful plugin :)

**Comment by EddyVerbruggen** [comment]
Nice!
