### ISSUE TITLE
any plan on hide event or callback

### ISSUE THREAD

**Issue by zero7u** [EddyVerbruggen/Toast-PhoneGap-Plugin#48]
Most of time, I need a hide callback rather than onError, any plans? Thanks!

**Comment by EddyVerbruggen** [comment]
Could you please elaborate on the uses of such a feature?

You can emulate it yourself btw by setting an appropriate value for `setTimeout` when showing the toast.

**Comment by zero7u** [comment]
There is a login form, and when I click submit button without entering anything, a toast will show 'please enter your name'. The question is, when I submit twice quickly, the toast will show one by one, the demand is, when I submit the second time, first toast should hide immediately, so I need to know when the first toast hided. I used ```setTimeout``` for now, and it worked fine.
