### ISSUE TITLE
doc out of date?

### ISSUE THREAD

**Issue by zero7u** [EddyVerbruggen/Toast-PhoneGap-Plugin#49]
when I install the plugin using:
````cordova plugin add nl.x-services.plugins.toast````
I will get a outdated version, while using the following code, will get the right version:
````cordova plugin add https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git````

please check it, thanks.

**Comment by EddyVerbruggen** [comment]
If your Cordova CLI is up to date that first command should fetch the latest stable plugin version from npm (long story). The latter simply grabs the master branch with any 'nightly' commit.
