### ISSUE TITLE
Make the next toast hiding the current one

### ISSUE THREAD

**Issue by tosrn** [EddyVerbruggen/Toast-PhoneGap-Plugin#50]
Hello,

great plugin! I'm having some (noob) trouble with multiple toasts though (on Android).

I would like the next toast to erase / replace the previous one if it's still being shown. I tried using window.plugins.toast.hide(); before showing the new toast but it hides the previous AND next one (basicaly nothing appears) 

Am I missing something?

**Comment by EddyVerbruggen** [comment]
Can you show the code which hides and shows the toast?

**Comment by tosrn** [comment]
Sure, thanks for the fast answer!

(I'm also using this controller to play an audio file first)

 $scope.play = function(src,message) {
        var media = new Media(src, function onSuccess() {
               // release the media resource once finished playing
               media.release();
            },
            function onError(e){
                console.log("error playing sound: " + JSON.stringify(e));
            });
         media.play();
         // TOAST
         window.plugins.toast.hide();
        $cordovaToast.show(message, 'long', 'bottom').then(function(success) {
            console.log("The toast was shown");
        }, function (error) {
            console.log("The toast was not shown due to " + error);
        });     
    };

**Comment by EddyVerbruggen** [comment]
I'm guessing you need to put that `showLongBottom('txt')` call in the successcallback of the `hide` function, since those Cordova functions are asynchronous:

```js
..hide(function() {
  // ..show here
});
```

**Comment by tosrn** [comment]
Sorry didn't managed to make it work.

Is that what you meant?

```javascript
$cordovaToast.hide().then(function(success) {
          $cordovaToast.show(message, 'long', 'bottom');
        });

**Comment by EddyVerbruggen** [comment]
I don't think ngCordova supports the `hide` function, so try this (didn't test this code, just typed it here):

```js
window.plugins.toast.hide(function() {
  // you're now in the succes callback handler of the 'hide' function
  $cordovaToast.show(message, 'long', 'bottom');
});
```
