### ISSUE TITLE
Request: update installation path

### ISSUE THREAD

**Issue by Duncank** [EddyVerbruggen/Toast-PhoneGap-Plugin#52]
When installing the plugin via CLI with "cordova plugin add nl.x-services.plugins.toast" it tells me that it has been renamed and I may not be getting the latest version. I should use 'cordova plugin add cordova-plugin-x-toast'.

**Comment by EddyVerbruggen** [comment]
Does the error go away if you follow that advice?

**Comment by Duncank** [comment]
Yes, when I use the second command it works. It installs the plugin with the first one as well, but I'm not sure it's the same version.

**Comment by EddyVerbruggen** [comment]
Readme updated  :+1:
