### ISSUE TITLE
Toast gets hidden behind camera view

### ISSUE THREAD

**Issue by hessius** [EddyVerbruggen/Toast-PhoneGap-Plugin#53]
I'm using the plugin to display feedback when using a barcode scanner in continuous mode, i.e. the barcode scanner keeps scanning even if it matches an item and a toast notifies the user of the match.

This works great when initiating the first toast after the camera view.

However, if a user closes the camera view and reopens the camera view, the camera view will be shown above the toast, thus hiding visual feedback from the user. Is there any way to make the toast continue to be displayed in the foreground?

**Comment by cvaliere** [comment]
Hi @hessius,
Do you still encounter the problem ?
Could you precise which barcode scanner you're using in continuous mode ?

**Comment by hessius** [comment]
Hi! @cvaliere for some reason I didn't get a notification of this mention, anyway - Better late than never!
I'm using this barcode scanner https://github.com/manateeworks/phonegap-mwbarcodescanner
