### ISSUE TITLE
#42 Again/Still? Toast won't show in front of InAppBrowser on iOS

### ISSUE THREAD

**Issue by dgerding** [EddyVerbruggen/Toast-PhoneGap-Plugin#55]
Hi,
I don't know if this is known behavior or if a fix is possible, but Toast elements don't show "in front of" an inAppBrowser instance if it's open.  Testing on an old iPhone running iOS 9.

If this is a "can't be fixed" issue could you let us know so I can figure out a workaround?

Thanks,
Dave G

**Comment by EddyVerbruggen** [comment]
Hi Dave,

You made me look at this again and I was able to find a fix this time. Well, it did work on iOS8 IIRC, but iOS9 was indeed broken.

Fix available in plugin version 2.2.1.

Btw, you may also be interested in [this plugin](https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller), depending on your needs.

Thanks for reporting this,
Eddy
