### ISSUE TITLE
Show toast when app is in background

### ISSUE THREAD

**Issue by ferryfax** [EddyVerbruggen/Toast-PhoneGap-Plugin#56]
I know its intentional that toasts from this plugin don't show when an Android app is paused but I have an app that does a long file upload and I would like to allow the user to switch to another activity and still see a toast when the upload is finished. Is it just a case of removing the "isPaused" check in the execute method of the plugin?

**Comment by EddyVerbruggen** [comment]
I don't think that'll reliably work. Feel free to try though.
