### ISSUE TITLE
Error: [$injector:unpr] Unknown provider: $cordovaToastProvider

### ISSUE THREAD

**Issue by vandervidi** [EddyVerbruggen/Toast-PhoneGap-Plugin#57]
I cant get this to work. I get the following error:
Error: [$injector:unpr] Unknown provider: $cordovaToastProvider <- $cordovaToast <- createNewCtrl
http://errors.angularjs.org/1.4.3/$injector/unpr?p0=ordovaToastProvider%20%3C-%20%24cordovaToast%20%3C-%createNewCtrl

I have injected $cordovaToast into my controller.

angular.module('myApp', [])
.controller('MyController', ['$cordovaToast', function ($cordovaToast) {
  // Do something with $cordovaToast
}]);

Any ideas how to fix this?

**Comment by EddyVerbruggen** [comment]
That's not an error related to this plugin, rather an indication you're not loading ngCordova.
