### ISSUE TITLE
Cannot read property 'toast' of undefined

### ISSUE THREAD

**Issue by yokesharun** [EddyVerbruggen/Toast-PhoneGap-Plugin#58]
apart from index.html the toast is not working

error:

"Uncaught TypeError: Cannot read property 'toast' of undefined", source: file:///android_asset/www/sliders.html (45)

**Comment by EddyVerbruggen** [comment]
Hi, without more info it's hard to tell as it can have many causes.

The best place to check for this kind of issues is StackOverflow, here's a pre-cooked search on this topic: http://stackoverflow.com/search?q=cordova+plugin+undefined

Things to check:

- Are you running on a device in a standalone app (not a companion app)?
- Do you have a reference to `cordova.js` in `sliders.html`?
- Is that file actually present and the correct one for your platform (not relevant when using build.phonegap.com)
- Is the plugin actually present in `cordova_plugins.js` (not relevant when using build.phonegap.com)?
- Do you wait for `deviceready` before invoking the plugin (and does that even fire at all)?
