### ISSUE TITLE
i didn't get any toast message in ios app. 

### ISSUE THREAD

**Issue by manojrejinthala** [EddyVerbruggen/Toast-PhoneGap-Plugin#64]

**Comment by manojrejinthala** [comment]
HI i used this plug in my app.i get toast messages in android application but i dint get any toast message in my ios app.i developed app using ionic framerwork

**Comment by peepsilog** [comment]
Try encapsulating the call of the toast message within a timeout.
Like:
        $timeout(function () {
            $cordovaToast.showLongCenter('I have a timeout');
        }, 1000);

**Comment by DHFW** [comment]
Hi @EddyVerbruggen, I have different problem. On iOS 9.2 (iPhone 5S, iPhone 6S) I can trigger the Toast, but is not showing, unless I push the home button. Then it is showing (briefly when the app is "closing"). When I immediately click on the app icon again, it is showing and then disappears (as expected). I use ngCordova in an Ionic project.
Is there a fix for this?
The solution of @peepsilog didn't have any effect.

**Comment by EddyVerbruggen** [comment]
@DHFW intersting case - perhaps another plugin is interfering with this one. Can you do a `cordova plugin list` and dump the result here? Better still, can you share your platforms/ios folder with me so I can reproduce it?

**Comment by DHFW** [comment]
@EddyVerbruggen, this is de cordova plugin list: 
cordova-plugin-x-toast 2.3.1 "Toast"
I only use one! So no interference there.
I can share the folder. Where can I send it to?

**Comment by EddyVerbruggen** [comment]
eddyverbruggen at gmail.com plz

**Comment by Furqankhanzada** [comment]
@EddyVerbruggen same issue with me any quick solution for this ?

**Comment by EddyVerbruggen** [comment]
Can you mail a little project reproducing this issue please?
