### ISSUE TITLE
Success callback not triggered when toast tapped in Android

### ISSUE THREAD

**Issue by tolomir** [EddyVerbruggen/Toast-PhoneGap-Plugin#65]
Hello,
In iOS works smoothly but when I tap the toast in Android the success callback is not triggered!
What could be the reason? Any clue to solve it?
Thanks!

**Comment by EddyVerbruggen** [comment]
Do you see this on multiple devices or a specific one? Trying to reproduce but no luck so far..

**Comment by jpost** [comment]
I am seeing this as well on my Nexus 5X.

**Comment by tolomir** [comment]
In my case it is a Vodafone Smart Prime 6 (Android 5.0.2). Hope it helps!
Thanks!

**Comment by EddyVerbruggen** [comment]
Oh dear, seems like the Toast can no longer receive an 'onTouchEvent' in the latest versions.. I need to think of a different way to achieve the same.

**Comment by EddyVerbruggen** [comment]
I'd love you guys to test 2.3.2 which adds support for the click event on Android 5+. I tested the previous implementation on 4.4.4 and 4.1, so it's a bit of a bummer I missed that.

**Comment by jpost** [comment]
After installing version 2.3.2 of the plugin, the success callback is fired as expected on all 3 of my testing devices I listed previously. Thanks for the quick turnaround!

**Comment by EddyVerbruggen** [comment]
@jpost Thanks for the quick test!
