### ISSUE TITLE
EXC_BAD_ACCESS error

### ISSUE THREAD

**Issue by jorgecachoh** [EddyVerbruggen/Toast-PhoneGap-Plugin#66]
Hi,

When trying to use Toast plugin in an Ionic app on iOS I'm getting EXC_BAD_ACCESS error (the error appears when executing Toast plugin but appears on cordova-plugin-app-event plugin code).

![captura de pantalla 2016-01-24 a las 11 25 15](https://cloud.githubusercontent.com/assets/5285725/12535749/c8c45d60-c28d-11e5-98da-ddb175b8faf2.png)

The plugin is working ok for Android version and also I have another Cordoba plugings running for Android an iOS on the same project without any error.

Doy you know how can I avoid this error on iOS?

**Comment by jorgecachoh** [comment]
It seems Toast plugin hasn't any dependence from cordova-plugin-app-event plugin but Local Notification plugin yes. In my app I am using de.appplant.cordova.plugin.local-notification so cordova-plugin-app-event is also installed and the issue appears when executing Toast plugin ;-(

I don't know if anyone has been able to use both Toast and Local Notification plugins installed on the same app and get them work on iOS platform (on Android there is no collide) ...

**Comment by EddyVerbruggen** [comment]
Hi, seems to be a bug in the app-event plugin - folks are [reporting](https://github.com/katzer/cordova-plugin-app-event/issues/1) [issues](https://github.com/katzer/cordova-plugin-app-event/issues/3) in that report with the same error and the maintainer has [tried to fix it](https://github.com/katzer/cordova-plugin-app-event/commit/9dd566f836bfe0bf2f217e9ef10dcdb6a38ce467).

However folks report it doesn't work yet (you're using the latest code, so including that 'fix'), but there is also a [pull request that seems to fix it](https://github.com/katzer/cordova-plugin-app-event/pull/4) but it's not released yet, so perhaps watching that PR is the best thing to do.

**Comment by roysG** [comment]
same for me, any updates?

**Comment by EddyVerbruggen** [comment]
@roysG you should look for updates [here](https://github.com/katzer/cordova-plugin-app-event/pull/4)

**Comment by DharmendraVaishnav91** [comment]
any update facing same issue

**Comment by EddyVerbruggen** [comment]
@DharmendraVaishnav91 read my previous comment

**Comment by DharmendraVaishnav91** [comment]
Has it merged with the master branch which we are using

**Comment by EddyVerbruggen** [comment]
@DharmendraVaishnav91 From reading it I can conclude it hasn't. Please watch the other issue as I have no control over it.

**Comment by DharmendraVaishnav91** [comment]
can you please suggest me how can I temporary remove this bug.

**Comment by katzer** [comment]
@DharmendraVaishnav91 I've released a new version including the fix.

**Comment by EddyVerbruggen** [comment]
@katzer much appreciated!

**Comment by DharmendraVaishnav91** [comment]
Thanks @katzer
