### ISSUE TITLE
styling.opacity is meanless

### ISSUE THREAD

**Issue by fattalgazi** [EddyVerbruggen/Toast-PhoneGap-Plugin#75]
Hi there,

You implemented animation of toast like this, 
```
    [UIView animateWithDuration:CSToastFadeDuration
                          delay:0.0
                        options:(UIViewAnimationOptionCurveEaseOut | UIViewAnimationOptionAllowUserInteraction)
                     animations:^{
                         toast.alpha = CSToastOpacity;
                     } completion:^(BOOL finished) {
                         NSTimer *timer = [NSTimer scheduledTimerWithTimeInterval:duration target:self selector:@selector(toastTimerDidFinish:) userInfo:toast repeats:NO];
                         // associate the timer with the toast view
                         objc_setAssociatedObject (toast, &CSToastTimerKey, timer, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
                     }];
```

toast.alpha = CSToastOpacity; will go to predefined value 0.8, so our styling.opacity value is meanless. Can you set toast.alpha to "styling.opacity" value ? When I set to styling.opacity : 1.0 toast view is still transparent because of this reason.

Thanks.

**Comment by fattalgazi** [comment]
Let me explain with screenshots, I set opacity to 1.0 in styling object, but toast looks like that because of 

````
toast.alpha = CSToastOpacity;
````

code in your implementation. (alpha goes from 0.0 to 0.8)

![img_4172](https://cloud.githubusercontent.com/assets/3602109/13147306/605d470e-d661-11e5-8331-da960ef38038.PNG)

--------------


![img_4173](https://cloud.githubusercontent.com/assets/3602109/13147307/60617d60-d661-11e5-8e6f-e54beacb42c7.PNG)

**Comment by EddyVerbruggen** [comment]
I'll look into it, thanks!

**Comment by EddyVerbruggen** [comment]
Fixed in 2.4.2

**Comment by fattalgazi** [comment]
You are just awesome, you always answer issues and solve them very fast, please add a donate button. Keep being amazing.

**Comment by EddyVerbruggen** [comment]
Thanks man, I'll do my best :)

Donate button has been added to the readme (thanks for the idea!).
