### ISSUE TITLE
Android toast with disabled notification

### ISSUE THREAD

**Issue by pbakondy** [EddyVerbruggen/Toast-PhoneGap-Plugin#77]
Toasts are disabled if notifications are disabled for an app on Android platform
https://code.google.com/p/android/issues/detail?id=35013
### Expected behaviour

The `show()` method should return with the errorCallback when notifications are disabled for the current app.
### Actual behaviour

No toast displayed, successCallback called.
#### OS versions

Android 4.2.2
Android 6.0

**Comment by EddyVerbruggen** [comment]
OMG that's bad. I mean, why does Android think that's a good idea at all?

Thanks for bringing this to my attention.

**Comment by Hirbod** [comment]
That is totally crap.. Didn't know that till now

**Comment by laberg** [comment]
any update ?

**Comment by EddyVerbruggen** [comment]
@laberg It's the Android issue tracker (link above) where you should ask this.
