### ISSUE TITLE
Bug in Android with cordova 3.5.x

### ISSUE THREAD

**Issue by ghost** [EddyVerbruggen/Toast-PhoneGap-Plugin#8]
Can't make it work and I've seen that there is a difference in the name. The folder created is nl.x-services.plugins.toast. I think it should be nl.xservices.plugins.toast right?

**Comment by simonshout** [comment]
I don't mean to dig up old discussions but I stumbled across this while I was searching for a solution to the same problem. I used the "cordova plugin add nlx.." and just tried to run a window.plugins.toast.showShortCenter(msg) in a .js file from a button click. I get the same undefined property error. Was there a solution to this?

**Comment by EddyVerbruggen** [comment]
HI, that depends. Are you running on a real device? Which platform? Did you run `cordova prepare`..

**Comment by simonshout** [comment]
Hello,

I'm running an avd (nexus 7/android 19). I ran cordova prepare, though not
right after I installed the package. I hastily tried emulating it once
before I did. I also tried to insert the one-liner into the device prepared
logic from the stock cordova app as a quick test to see if it was my js
file with the error; it had the same obscure error.

Regards,
Simon

**Comment by EddyVerbruggen** [comment]
You're best off trying from scratch with a new `cordova create..` command, add the plugin and deploy to a real device. If that works, try to find what's different..

**Comment by kartagis** [comment]
Hi, sorry to hijack this issue but I have the very same issue; only on a 4.4.4. I used the exact same line in README.md to test and I commented out my own js file, but still no dice.

**Comment by luckyforu** [comment]
AM testing the plugin on my android device 5.1 and i get the same issue, $window.plugins undefined

**Comment by fmtoffolo** [comment]
Was this fixed? I have to use `window.plugins.toast` to get it working.
