### ISSUE TITLE
Receiving a callback when a Toast is tapped not trigger in Android

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/Toast-PhoneGap-Plugin#80]
hi @EddyVerbruggen 
I am using =>
Cordova Cli 6.0 + Cordova-Android 5.1.1 + cordova-plugin-crosswalk-webview 1.5.0 + cordova-plugin-x-toast 2.4.2 + Android 4.4.2 (my device)

according to this
https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin#receiving-a-callback-when-a-toast-is-tapped
**Receiving a callback when a Toast is tapped**

I test many times，iOS no problem at all，but in Android，when Toast is tapped but no trigger 
```
if (result && result.event) {
        console.log("The toast was tapped");
        console.log("Event: " + result.event); // will be defined, with a value of "touch" when it was tapped by the user
        console.log("Message: " + result.message); // will be equal to the message you passed in
        console.log("data.foo: " + result.data.foo); // .. retrieve passed in data here
      }
```

**Comment by EddyVerbruggen** [comment]
Something changed on Android. I've adjusted the implementation and now it should work better. Available in 2.5.0 (releasing it in a minute).

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
I tried 2.5.0 version and tried many times but seem still not work
I am using =>
Cordova Cli 6.0 + Cordova-Android 5.1.1 + cordova-plugin-crosswalk-webview 1.5.0 + cordova-plugin-x-toast 2.4.2 + Android 6.0 (my device)

**Comment by blattmann** [comment]
Same here.
Events are working fine under iOS but not on Android.
2 Samsung devices: Android 5.1.1 and Android 6.0.1

**Comment by EddyVerbruggen** [comment]
Are you able to debug it a little in Android Studio?

**Comment by blattmann** [comment]
@EddyVerbruggen 
I was now building the app in Android studio. In the Emulator the click on a toast message works as expected. If I build it with the ionic CLI (`ionic build android`) and then install it on my physical device the click on the toast message is not fired.

**Comment by EddyVerbruggen** [comment]
I justed (perhaps) fixed an issue on Android < 5 devices regarding the tap.. couldn't reproduce on Android 5+ though.

**Comment by peterturquoise** [comment]
Same issue fr me on plugin v 2.5.2. The click on toast callback is fired in iOS but not Android. I'm using an Android 5.1 device.

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
still some trouble in android (even 6 version)
same with @blattmann and @peterturquoise

**Comment by bau720123** [comment]
hello @EddyVerbruggen 
2 months passed
anything wrong ?

**Comment by EddyVerbruggen** [comment]
I can't reproduce it. That's the problem. If someone can please at least attempt to fire up Android Studio and try to fix it.

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
just like @blattmann said
in the Emulator the click on a toast message works as expected
but my physical device（mine is HTC M9，Android 6.0） the click on the toast message is not fired（**Android > 5**）

**Comment by EddyVerbruggen** [comment]
I can't test that since I don't currently own an Android 6 device.

**Comment by bau720123** [comment]
thanks @EddyVerbruggen reply
well...
maybe if you have free time and one day have a Android 6 device，you can try for this
Cheers

**Comment by insaneinc01** [comment]
Same issue on Android OS 6.0 :( 
(Android LG G3)

**Comment by ajaybhalerao12** [comment]
Hi Eddy,
I am facing the same issue on Android 6.0, click on toast callback is not called.
Could you please check.
I am using cordova-plugin-x-toast 2.6.2,

Thanks in advance.
