### ISSUE TITLE
Take keyboard view as reference

### ISSUE THREAD

**Issue by fredericksauvage** [EddyVerbruggen/Toast-PhoneGap-Plugin#84]
iOS 9.2, iphone 6:

If the keyboard is opened when a toast message is displaying, the toast frame "take" the keyboard view as reference. So, if the toast frame position is setted to "top", the toast message is displayed on top of keyboard instead of top of screen.

**Comment by EddyVerbruggen** [comment]
Not in my test it's not.. can you share an example where this happens? Preferrably the platforms/ios folder so I can just run it in Xcode and see the issue?

**Comment by Hirbod** [comment]
Maybe disableScroll or something is active/deactivated while doing this (which could lead into different results)
