### ISSUE TITLE
Is there anyway to get a significantly larger font on IOS and Android?

### ISSUE THREAD

**Issue by rwillett** [EddyVerbruggen/Toast-PhoneGap-Plugin#86]
Hi,

We are using the Toast plugin to put up traffic information and alerts on our app. It works well and we have no coding issues.

What we would like would be the ability to create a significantly larger message on the screen.  e.g. something with a very large font so the user is very much aware that something is happening and can see it when the screen is attached to a car windscreen.
 
At the moment the message is very small and the user can't easily read it, especially on the new iPhone 6s models. The sort of size we are after would be 1/4 of the screen or something. Since we only have a few characters to display, speed limit, we could make the font very large without it wrapping.

We've searched the archives for anybody else wanting this but can't see anything which surprised us a little, as we thought lots of people might want it. Shows what little we know :)

Thanks again for a great plugin

Rob

**Comment by EddyVerbruggen** [comment]
Great idea but indeed you're first.

I'll push an update in about 8 hours which will have a `textSize` option for iOS and Android.

**Comment by rwillett** [comment]
Eddy,

Thanks of the prompt and helpful reply. 

That would be great. Much appreciated. 

We've just sent a donation to help with pizza and beer.

All the best

Rob

**Comment by EddyVerbruggen** [comment]
Much appreciated 🍕 🍺

**Comment by EddyVerbruggen** [comment]
Published!

**Comment by rwillett** [comment]
Just to confirm that the fontSize worked fine. Thanks.

We also discovered that \n works in strings so we get multline 'Toasts'.

One thing we noticed though is that we lose the centering of text.

Here's an example of what we are doing. The fontsize is great (its 30pt in the picture), the red background is just what we are after, but the top line, A40, is left justified, where as it would be nice to justified on the centre.

For information we are tracking average speed through a set of speed cameras in the North West of London. The cameras do number plate recognition and work out your average speed over 10 miles (thats a long way to do 40mph on basically a dual carriage way). The penalties for breaking the average speed limit are quite high, hence this is a free option for our free app, or it will be once we finish writing it. 

Is this a CSS option or do we need to buy you more Pizza and beer?

![screen shot 2016-04-28 at 22 08 25](https://cloud.githubusercontent.com/assets/668923/14901582/03632762-0d8e-11e6-816f-c8efce655667.png)

**Comment by EddyVerbruggen** [comment]
Wow very nice app and awesome use of this plugin!

The text on iOS is now center aligned when you pull from the master branch of this repo (I didn't check Android). I don't say no to more 🍺 and 🍕!

**Comment by rwillett** [comment]
Thanks, we've downloaded and tested it and looks good. More pizza and beer have been sent :)

We're launch this version of our app sometime in the next few weeks as we iron out the bugs in working out the average speed on roads. It's surprisingly difficult to work out which road you are on, which direction you are travelling in and avoiding roads that cross, bridges, roads with different speed limits on different sections and on different sides of the road. At least our display of information is resolved :)

All the best and thanks for helping

Rob

**Comment by EddyVerbruggen** [comment]
Is your app limited to London / the UK? It looks super useful!

Good luck squashing the last few 🐛 🐞 and thanks again for sponsoring this plugin!

**Comment by rwillett** [comment]
Eddy,

The app is London based at the moment. It learns your routes to work or wherever and the times you travel, sends you personalised travel updates, along with predicted times to clear, we've built an analysis engine to process the traffic disruptions and automatically categorise them into serious, major and minor issues, it handles the London congestion zone, which most drivers have to pay if you cross into it during working hours, it provides live video (as opposed to just static pictures) feeds of traffic cameras. 

Currently we're working on average speed cameras which are becoming more common in London. The latest ones go for 10Km which is a long way to drive at 40mph. The problem is that the zones are different in each direction and change along the route. The maths and GPS/DB issues become 'interesting'. 

We've very much into Big Data, maps and mobile, though I personally am happier at the back end.

We'd love to take it to other cities worldwide but we need to raise finance first. If we can show it works in London, then its easier to get it working in New York, San Francisco, Paris, Berlin, Tokyo etc. 

We've just launched a new version about two hours ago on the Apple Store and on Google Play. We;re happy with the new version and we'll be even happier with the next one.

Rob

**Comment by EddyVerbruggen** [comment]
Hey Rob,

Thanks for elaborating and I don't envy the traffic situation in London. I'm sure it will be a very useful app for Londoners. Please share the name of the app and I'll tweet about it.

Cheers,
Eddy

**Comment by rwillett** [comment]
Eddy,

The app is called Jambuster, we have a Twitter feed @jambusterlondon and our website is www.jambuster.london. 

The app is only available on the Apple UK app store as well as the UK Google Play store. Since the app is dedicated to London it makes no sense for it to be available worldwide. 

Your plugin is currently used in the latest development version, which has average speed zones and not in the released version. We are expecting/hoping/praying to get the next version out in around two to three weeks. 

Your plugin works very well now, it was dead easy to put a large screen showing the users current speed, average speed, max speed and use different background colours to highlight going too fast (red) or OK (green).

Feel free to Tweet about us, the more people who know about the app the better. Its 100% free with no ads and no in-app purchases. We want to keep it that way and so the more people who use it the better.

All the best, enjoy the pizza and thanks for a great plugin.

Rob

**Comment by rwillett** [comment]
Eddy,

We've just been testing the Android version of our app and noticed that the formatting is left justified rather than centre justified. It looks just like the picture I posted seven posts up. Is this an easy fix please?

Thanks

Rob

**Comment by EddyVerbruggen** [comment]
Ha, I was wondering what it would do on Android. 

I'm at PhoneGap Day EU today but will look at it this week.

**Comment by rwillett** [comment]
Now you know :)

No rush, its a cosmetic issue.

Enjoy PhoneGap Day EU.

Rob

**Comment by EddyVerbruggen** [comment]
Hey Rob,

Back from the conference, had a blast :)

The Android alignment is now also playing nice if you pull a fresh copy from master.

Once that's been tested I'll do a new npm release.

Cheers,
Eddy

**Comment by rwillett** [comment]
Eddy,

I can confirm its working on Android. This is a screen shot from Genymotion using Lockito to simulate driving down a road in South East London.

![screen shot 2016-05-21 at 10 44 51](https://cloud.githubusercontent.com/assets/668923/15447639/20103ea8-1f41-11e6-80a6-71cf3c7cb7b2.png)

**Comment by EddyVerbruggen** [comment]
Nice!
