### ISSUE TITLE
The method setElevation(int) is undefined for the type View

### ISSUE THREAD

**Issue by mdudaycse** [EddyVerbruggen/Toast-PhoneGap-Plugin#87]
I am getting this error when I imported the new Java file

**The method setElevation(int) is undefined for the type View**

Device OS : Android

**Comment by EddyVerbruggen** [comment]
Are you using an SDK of API level lower than 21? Please update your local Android SDK in that case.

**Comment by mdudaycse** [comment]
Great, it worked when I changed target to 21 (target=android-21), but it affects another plugin (NetworkManager.java) , It would be really helpful if you are able to help me on this, both plugins are working with the target 19, If I swap the target either one of them not working.

**Comment by EddyVerbruggen** [comment]
You can leave your target to anything you want, as long as you're compiling against at least 21.

Are you referring to [this plugin](https://github.com/apache/cordova-plugin-network-information/blob/master/src/android/NetworkManager.java) you have a problem with?

**Comment by mdudaycse** [comment]
Yes the same Network Manager plugin. I don't have knowledge in Java, After
setting the target 21, Toast Plugin is working fine , but the network
manager plugin throws error, I guess there might be some library files
needs to be loaded, I could not resolve it, that's what I requested for
your help, Thanks a lot for your time

Thanks and Regards
*Udhayakumar Manoharan*

*Cognizant Technology Solutions.Mobile : +1 415-230-9391*

**Comment by EddyVerbruggen** [comment]
Just to be sure: when you say 'target', did you change the SDK in Android Studio, or did you change the target in AndroidManifest.xml? I was referring to the first.

**Comment by mdudaycse** [comment]
I changed the target in project.properties file target=android-21, I am not
using android studio, I am using eclipse ADT. Check the below screenshot,


Android XML File
<uses-sdk android:minSdkVersion="11" android:targetSdkVersion="21"/>

but in project build target , could not see API Level 21
[image: Inline image 1]

[image: Inline image 2]

Udhay

Thanks and Regards
*Udhayakumar Manoharan*

*Cognizant Technology Solutions.Mobile : +1 415-230-9391*
