### ISSUE TITLE
Can we use images in Toast popups?

### ISSUE THREAD

**Issue by rwillett** [EddyVerbruggen/Toast-PhoneGap-Plugin#90]
I think the answer is no, but #22 seems to imply that there is IOS code for doing this. 

I've searched through the rest of the issue list and the API docs and can't see anything that references images so am assuming that this is not possible and #22 is poorly worded (as well as being from a long time ago).

We did a couple of experiments by including a URL with and without $sce.trustAsResourceUrl() and didn't get it to work so it doesn't look like its there. Mind you as there's no doc, we might never have got it right :)

It would be good to get confirmation we can't do this though. 

Also would it be a massive piece of work to code this up? I suspect we aren't the only people who want it. Perhaps a crowdfunding effort? 

Comments and views welcomed.

Rob

**Comment by EddyVerbruggen** [comment]
On iOS this shouldn't be too hard but on Android I think it would require some more work. It's indeed not currently available nor planned at the moment.

**Comment by Hirbod** [comment]
+1

**Comment by frey1esm** [comment]
+1
