### ISSUE TITLE
Crash app Android 6x

### ISSUE THREAD

**Issue by kingstakh** [EddyVerbruggen/Toast-PhoneGap-Plugin#92]
### Expected behaviour
Application crash on Android 6x

### Actual behaviour
Tell us what happens instead. Provide a log message if relevant.

### I'm seeing this behaviour on

- [ ] iOS device
- [ ] iOS sim
- [x] Android device
- [ ] Android sim

#### Hardware models
Xiaomi Mi3w

#### OS versions
Android 6.0.1

### I'm not a dummy, so I've checked these
- [ ] It happens on a fresh Cordova CLI project as well.
- [x] I'm waiting for `deviceready` to fire.
- [ ] My JavaScript has no errors (`window.onerror` catches nothing).

**Comment by fabriciopaulo** [comment]
I'm also having this problem, when the toast is called too many on short time, it crashes the application.

**Comment by EddyVerbruggen** [comment]
I tried 2 simulators running Android 6 (API 23) but wasn't able to crash those while invoking `showToast` many times in a very short time.

Do you have sample code reproducing the error?

**Comment by EddyVerbruggen** [comment]
Now also tested a Nexus 6P device with Android 7 without issues.
