### ISSUE TITLE
Toast not showing on Android ?

### ISSUE THREAD

**Issue by efbi** [EddyVerbruggen/Toast-PhoneGap-Plugin#97]
Hi,

I'm using your plugin with Ionic but it only Work with ionic view. When i build my app in android nothing appears..

**Comment by EddyVerbruggen** [comment]
Have you added the plugin to your project? How?

**Comment by siatstcolumb** [comment]
Sorry to report that it's not working for me either. It used to work great with the previuos version "nl.x-services.plugins.toast" 2.0.2. 
I'm using Phonegap, testing on a Moto G Android 5.1 with the following config.xml entry:
<gap:plugin name="cordova-plugin-x-toast" source="npm" />
I've tried reverting to the old version, but this is no longer working either.

**Comment by siatstcolumb** [comment]
My config.xml: `<gap:plugin name="cordova-plugin-x-toast" source="npm" />`

**Comment by siatstcolumb** [comment]
Workaround found: my previous code called the toast plugin from a wrapper function that used string variables for the duration and position parameters. When I substituted string literals instead of variables for these parameters the code started working again. Mystifying.

**Comment by mparpaillon** [comment]
@siatstcolumb I have the same problem and I don't understand your workaround. How did you fixed this please ?

**Comment by siatstcolumb** [comment]
My original code that had stopped working:

Library.toaster = function (msg, param1, param2) {
    // param1: 1=center/short, 2=center/long, 3=bottom/short
    // param2: If passed in call, param1 & param2 are string args for window.plugins.toast.show,
    //         otherwise param2 is internally set by code below
    try {
        if (!param2) {
            param2 = param1 > 2 ? 'bottom' : 'center';
            param1 = param1 === 2 ? 'long' : 'short';
        }
        //
        window.plugins.toast.show(msg, param1, param2);
        //
    } catch (e) {
        alert(e.message);
    }
}

Amended working code:

Library.toaster = function (msg, param1, param2) {
    // param1: 1=center/short, 2=center/long, 3=bottom/short
    try {
        if (param1 == 1) {
            window.plugins.toast.show(msg, 'short', 'center');
        } else if (param1 == 2) {
            window.plugins.toast.show(msg, 'long', 'center');
        } else if (param1 == 3) {
            window.plugins.toast.show(msg, 'short', 'bottom');
        }
        //
    } catch (e) {
        alert(e.message);
    }
}

**Comment by siatstcolumb** [comment]
@mparpaillon above is my code before and after

**Comment by northkode** [comment]
Getting the same issue, no toast showing for android. Used to work in older version. 
Ill try and down grade some how.

**Comment by danilopolani** [comment]
+1 not working with Ionic 2. I tried changing position and duration, but nothing.

Simple code:

```
import { Toast } from '@ionic-native/toast';

@Injectable()
export class SyncService {
    constructor(
        private toast: Toast
    ) { }

    sync() {
        this.toast.show('Sync...', '3000', 'center');
    }
}
```

May be the z-index (I don't know if it render a native toast or a CSS-like)? The `sync` method works correctly, the ionic toast works, but it's too invasive, so I prefer to use this.

**Comment by drquochoai** [comment]
anyone have any solutions?

**Comment by danilopolani** [comment]
@EddyVerbruggen  any idea? Could be a problem of Ionic or of this repo?

**Comment by marcosafmartins92** [comment]
Hi people, try to use this: https://ionicframework.com/docs/api/components/toast/ToastController/

**Comment by phonic** [comment]
+1 Any progress on this?

**Comment by EddyVerbruggen** [comment]
@phonic Does it work with plain Cordova? If not there's a problem in the plugin. If it does work, there's a problem with the Ionic wrapper.

**Comment by phonic** [comment]
@EddyVerbruggen  I'll give it a try later...

**Comment by phonic** [comment]
@EddyVerbruggen Yeah its working on plain cordova

**Comment by EddyVerbruggen** [comment]
Thanks, @phonic 👍 

Must be a problem in some higher layer then..

**Comment by phonic** [comment]
@EddyVerbruggen I've found the reason (in my case)... When you use it with the ionic native wrapper (@ionic-native/toast), you have to subscribe to the show observable at least, to display the toast successfully. Otherwise it wont appear...

```
this.toast.show(`I'm another toast`, '8000', 'bottom').subscribe(
                  toast => {
                    console.log(toast);
                  }
                );
```

**Comment by yesisinterestings** [comment]
@EddyVerbruggen I use the plugin to find a problem，my android App frist hide ， plugin is work。but，The next operation is the same，plugin is not work。 sorry ，my English is not good . i hope you ask my question

**Comment by narenderreddych** [comment]
@EddyVerbruggen I am using this plugin in Phonegap earlier its worked fine Now not working. I put a toast on button click. If I single tap button not showing a toast But clicking on multiple times it's showing but delay in time.

Please give any solution

**Comment by DGGohil** [comment]
Its not working though i have applied with simple one line click code  window.plugins.toast.show('Hello there!','2000','center'); do i missing some tips. 
PS: i successfully installed and running x-toast 2.6.2 in my another app. i wonder waht do i missing,, please help.

**Comment by DGGohil** [comment]
> @EddyVerbruggen I am using this plugin in Phonegap earlier its worked fine Now not working. I put a toast on button click. If I single tap button not showing a toast But clicking on multiple times it's showing but delay in time.
> 
> Please give any solution

Remove this line from your index.html file meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;"> and add below one..
...
meta http-equiv="Content-Security-Policy" content="default-src * gap: ws: https://ssl.gstatic.com;style-src * 'unsafe-inline' 'self' data: blob:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;img-src * data: 'unsafe-inline' 'self' content:;media-src mediastream;">

**Comment by narenderreddych** [comment]
I tried with using meta tag but no success
please advise any solution or fix it

**Comment by DGGohil** [comment]
> I tried with using meta tag but no success
> please advise any solution or fix it

Where is your html and js file ?

**Comment by mwq27** [comment]
What part of the CSP is the important part? @EddyVerbruggen
